---
# Used as shared lock and last-run file
last_file: /ceph/system/ceph_snapshot.last

# Directories and how often they should be snapshotted, and for how long snapshots should be kept
# Times are in hours
paths:
  /archive:
    frequency: 48
    keep: 2160
  /home:
    frequency: 24
    keep: 720
  /scratch:
    frequency: 8
    keep: 168
